version: '3.8'

services:
  lxc-autoscale:
    image: lxc-autoscale  # Ensure that this image is built locally or available on a registry
    container_name: lxc-autoscale
    environment:
      POLL_INTERVAL: 300
      CPU_UPPER_THRESHOLD: 80
      CPU_LOWER_THRESHOLD: 20
      MEMORY_UPPER_THRESHOLD: 80
      MEMORY_LOWER_THRESHOLD: 20
      CORE_MIN_INCREMENT: 1
      CORE_MAX_INCREMENT: 4
      MIN_CORES: 1
      MAX_CORES: 8
      MIN_MEMORY: 512
      MIN_DECREASE_CHUNK: 512
      RESERVE_CPU_PERCENT: 10
      RESERVE_MEMORY_MB: 2048
      LOG_FILE: '/var/log/lxc_autoscale/lxc_autoscale.log'
      LOCK_FILE: '/var/lock/lxc_autoscale/lxc_autoscale.lock'
      BACKUP_DIR: '/var/lib/lxc_autoscale/backups'
      OFF_PEAK_START: 22
      OFF_PEAK_END: 6
      ENERGY_MODE: 'False'
      GOTIFY_URL: ''
      GOTIFY_TOKEN: ''
      IGNORE_LXC: ''
      BEHAVIOUR: 'normal'
      SMTP_SERVER: ''
      SMTP_PORT: 587
      SMTP_USERNAME: ''
      SMTP_PASSWORD: ''
      SMTP_FROM: ''
      SMTP_TO: ''
      UPTIME_KUMA_WEBHOOK_URL: ''
      USE_REMOTE_PROXMOX: 'False'
      PROXMOX_HOST: ''
      SSH_PORT: 22
      SSH_USER: ''
      SSH_PASSWORD: ''  # Consider using Docker secrets for sensitive data
      SSH_KEY_PATH: ''
    volumes:
      - /var/log/lxc_autoscale:/var/log/lxc_autoscale  # Ensure this directory is specific to your app
      - /var/lock/lxc_autoscale:/var/lock/lxc_autoscale  # Ensure this directory is specific to your app
      - /var/lib/lxc_autoscale:/var/lib/lxc_autoscale
      - /usr/local/bin:/usr/local/bin  # Map /usr/local/bin for your scripts and binaries
    restart: unless-stopped
