"""Constants used throughout the LXC autoscaling system."""

# File paths
DEFAULT_CONFIG_FILE = '/etc/lxc_autoscale/lxc_autoscale.yaml'
DEFAULT_LOG_FILE = '/var/log/lxc_autoscale.log'
DEFAULT_LOCK_FILE = '/var/lock/lxc_autoscale.lock'
DEFAULT_BACKUP_DIR = '/var/lib/lxc_autoscale/backups'

# Default scaling parameters
DEFAULT_POLL_INTERVAL = 300
DEFAULT_RESERVE_CPU_PERCENT = 10
DEFAULT_RESERVE_MEMORY_MB = 2048
DEFAULT_OFF_PEAK_START = 22
DEFAULT_OFF_PEAK_END = 6

# Default thresholds
DEFAULT_CPU_UPPER_THRESHOLD = 80
DEFAULT_CPU_LOWER_THRESHOLD = 20
DEFAULT_MEMORY_UPPER_THRESHOLD = 80
DEFAULT_MEMORY_LOWER_THRESHOLD = 20

# Default resource limits
DEFAULT_MIN_CORES = 1
DEFAULT_MAX_CORES = 4
DEFAULT_MIN_MEMORY = 512
DEFAULT_CORE_MIN_INCREMENT = 1
DEFAULT_CORE_MAX_INCREMENT = 2
DEFAULT_MEMORY_MIN_INCREMENT = 256
DEFAULT_MIN_DECREASE_CHUNK = 128

# Scaling behavior constants
DEFAULT_CPU_SCALE_DIVISOR = 2.0
DEFAULT_MEMORY_SCALE_FACTOR = 1.5
DEFAULT_TIMEOUT_EXTENDED = 60

# Behavior modes
BEHAVIOR_NORMAL = 'normal'
BEHAVIOR_CONSERVATIVE = 'conservative'
BEHAVIOR_AGGRESSIVE = 'aggressive'

# Behavior multipliers
CONSERVATIVE_MULTIPLIER = 0.5
AGGRESSIVE_MULTIPLIER = 2.0
OFF_PEAK_MULTIPLIER = 0.8

# SSH connection defaults
DEFAULT_SSH_PORT = 22
DEFAULT_SSH_TIMEOUT = 10
DEFAULT_COMMAND_TIMEOUT = 30

# Thread pool settings
DEFAULT_MAX_WORKERS = 8

# Validation limits
MIN_CPU_THRESHOLD = 0
MAX_CPU_THRESHOLD = 100
MIN_MEMORY_THRESHOLD = 0
MAX_MEMORY_THRESHOLD = 100
MIN_CORES_LIMIT = 1
MIN_MEMORY_LIMIT = 128

# Notification priorities
NOTIFICATION_PRIORITY_LOW = 3
NOTIFICATION_PRIORITY_NORMAL = 5
NOTIFICATION_PRIORITY_HIGH = 8

# Grace periods (in seconds)
DEFAULT_SCALE_OUT_GRACE_PERIOD = 300
DEFAULT_SCALE_IN_GRACE_PERIOD = 600

# Network configuration
NETWORK_TYPE_DHCP = 'dhcp'
NETWORK_TYPE_STATIC = 'static'